# Generated by Django 5.0.6 on 2024-06-01 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_table_number_alter_table_personcapacity'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiter',
            name='charge',
            field=models.CharField(choices=[('MG', 'MANAGER'), ('AT', 'ADMINTABLES'), ('EX', 'EXTRA')], default='EX', max_length=2, unique=True),
        ),
        migrations.CreateModel(
            name='WaiterShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_date', models.DateField()),
                ('end_date', models.DateField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.restaurant')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.waiter')),
            ],
        ),
    ]
