# Generated by Django 5.0.6 on 2024-06-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_waiter_charge_waitershift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitershift',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='waitershift',
            name='star_date',
            field=models.DateTimeField(),
        ),
    ]
