# Generated by Django 5.0.6 on 2024-06-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_waitershift_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitershift',
            old_name='star_date',
            new_name='start_date',
        ),
    ]
