# Generated by Django 5.0.6 on 2024-06-04 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_bill_cost_alter_bill_finalcost_and_more'),
        ('users', '0006_alter_waiter_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipWaiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(blank=True, default=False)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.bill')),
                ('waiter', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.waiter')),
            ],
        ),
    ]
