# Generated by Django 5.0.6 on 2024-06-03 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_table_number_alter_table_personcapacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='finalCost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurants.order'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='tipPorcent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
